# Generated by Django 4.1.4 on 2023-01-12 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=5, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Invalid postal code')], verbose_name='Zip Code'),
        ),
    ]
